const restData = [
  {
    id: 1,
    restName: "Aavi",
    restRating: "4.6",
    expTime: "30-35 mins",
    restCuisines: "Kerala, South Indian",
    imgLink: "https://dummyimage.com/600x400/000/fff&text=Italian+Bistro",
  },
  {
    id: 2,
    restName: "Sushi Palace",
    restRating: "4.7",
    expTime: "20-25 mins",
    restCuisines: "Japanese, Sushi",
    imgLink: "https://dummyimage.com/600x400/000/fff&text=Sushi+Palace",
  },
  {
    id: 3,
    restName: "Burger Haven",
    restRating: "4.3",
    expTime: "25-30 mins",
    restCuisines: "American, Fast Food",
    imgLink: "https://dummyimage.com/600x400/000/fff&text=Burger+Haven",
  },
  {
    id: 4,
    restName: "Taco Fiesta",
    restRating: "4.6",
    expTime: "15-20 mins",
    restCuisines: "Mexican, Tex-Mex",
    imgLink: "https://dummyimage.com/600x400/000/fff&text=Taco+Fiesta",
  },
  {
    id: 5,
    restName: "Vegan Delight",
    restRating: "4.8",
    expTime: "35-40 mins",
    restCuisines: "Vegan, Healthy",
    imgLink: "https://dummyimage.com/600x400/000/fff&text=Vegan+Delight",
  },
  {
    id: 6,
    restName: "Curry House",
    restRating: "4.4",
    expTime: "30-35 mins",
    restCuisines: "Indian, Curry",
    imgLink: "https://dummyimage.com/600x400/000/fff&text=Curry+House",
  },
  {
    id: 7,
    restName: "Pizza Parlor",
    restRating: "4.5",
    expTime: "20-25 mins",
    restCuisines: "Pizza, Italian",
    imgLink: "https://dummyimage.com/600x400/000/fff&text=Pizza+Parlor",
  },
  {
    id: 8,
    restName: "Mediterranean Grill",
    restRating: "4.7",
    expTime: "25-30 mins",
    restCuisines: "Mediterranean, Grill",
    imgLink: "https://dummyimage.com/600x400/000/fff&text=Mediterranean+Grill",
  },
  {
    id: 9,
    restName: "Thai Terrace",
    restRating: "4.6",
    expTime: "15-20 mins",
    restCuisines: "Thai, Asian",
    imgLink: "https://dummyimage.com/600x400/000/fff&text=Thai+Terrace",
  },
  {
    id: 10,
    restName: "French Bakery",
    restRating: "4.8",
    expTime: "30-35 mins",
    restCuisines: "French, Bakery",
    imgLink: "https://dummyimage.com/600x400/000/fff&text=French+Bakery",
  },
];

export default restData;
